import jsPDF from "jspdf";

export const downloadBusinessSummaryPDF = (data: any) => {
    const doc = new jsPDF();
    const label = data.label;
    const summary = data.summary;
    const expenses = data.expenses;
    const sales = data.sales;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(74, 144, 226); // Primary blue color
    doc.text("Pharmino Business Summary", 105, 20, { align: "center" });

    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(`Report Period: ${label}`, 105, 30, { align: "center" });

    const status = summary.revenue.netProfitStatus;
    doc.setFontSize(10);
    doc.setTextColor(status === "PROFIT" ? 46 : 231, status === "PROFIT" ? 125 : 76, status === "PROFIT" ? 50 : 60); // Green or Red
    doc.text(`HEALTH STATUS: OVERALL ${status}`, 105, 37, { align: "center" });

    // Revenue Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Financial Overview", 20, 45);
    doc.setLineWidth(0.5);
    doc.line(20, 47, 190, 47);

    doc.setFontSize(12);
    doc.text(`Total Revenue: ${(Number(summary.revenue.totalRevenue) || 0).toFixed(2)}`, 20, 55);
    doc.text(`Total Sales: ${summary.revenue.totalOrders || 0}`, 20, 62);
    doc.text(`Total Discounts: ${(Number(summary.revenue.totalDiscount) || 0).toFixed(2)}`, 20, 69);
    doc.text(`Net Revenue: ${(Number(summary.revenue.netRevenue) || 0).toFixed(2)}`, 20, 76);
    doc.text(`Net Profit: ${(Number(summary.revenue.netProfit) || 0).toFixed(2)}`, 120, 55);
    doc.text(`Profit Margin: ${(Number(summary.revenue.profitMargin) || 0).toFixed(1)}%`, 120, 62);

    // Expenses Section
    doc.setFontSize(16);
    doc.text("Expenses Breakdown", 20, 90);
    doc.line(20, 92, 190, 92);

    doc.setFontSize(12);
    doc.text(`Total Expense: ${(Number(expenses.totalExpense) || 0).toFixed(2)}`, 20, 100);
    doc.text(` - Payroll: ${(Number(expenses.breakdown.payroll) || 0).toFixed(2)}`, 25, 107);
    doc.text(` - Product Cost: ${(Number(expenses.breakdown.productCost) || 0).toFixed(2)}`, 25, 114);
    doc.text(` - Others: ${(Number(expenses.breakdown.others) || 0).toFixed(2)}`, 25, 121);

    // Sales Analysis Section
    doc.setFontSize(16);
    doc.text("Analysis & Performance", 20, 135);
    doc.line(20, 137, 190, 137);

    doc.setFontSize(12);
    doc.text(`Most Sold (Qty): ${sales.mostSoldCategory || "N/A"}`, 20, 145);
    doc.text(`Top Category (Rev): ${sales.topRevenueCategory?.name || "N/A"} (${(Number(sales.topRevenueCategory?.revenue) || 0).toFixed(2)})`, 20, 152);
    doc.text(`Top Product Rev: ${(Number(sales.topProductRevenue) || 0).toFixed(2)}`, 20, 159);
    doc.text(`Items Returned: ${sales.returns || 0}`, 20, 166);
    doc.text(`Total Refunded: ${(Number(sales.totalRefunded) || 0).toFixed(2)}`, 20, 173);

    // Item List (Simplified)
    doc.setFontSize(14);
    doc.text("Top Selling Items", 20, 185);
    let y = 195;
    sales.items?.slice(0, 10).forEach((item: any) => {
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
        doc.setFontSize(10);
        doc.text(`${item.name} x ${item.quantity} - ${(Number(item.price) || 0).toFixed(2)}`, 20, y);
        y += 7;
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Pharmino POS System", 105, 290, { align: "center" });

    doc.save(`Business_Summary_${label.replace(/ /g, "_")}.pdf`);
};
