import jsPDF from "jspdf";

export const downloadBusinessSummaryPDF = (data: any) => {
    const doc = new jsPDF();
    const date = data.date;
    const summary = data.summary;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(74, 144, 226); // Primary blue color
    doc.text("Pharmino Business Summary", 105, 20, { align: "center" });

    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(`Report Date: ${date}`, 105, 30, { align: "center" });

    // Revenue Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Financial Overview", 20, 45);
    doc.setLineWidth(0.5);
    doc.line(20, 47, 190, 47);

    doc.setFontSize(12);
    doc.text(`Total Revenue: ${summary.revenue.totalRevenue.toFixed(2)}`, 20, 55);
    doc.text(`Total Orders: ${summary.revenue.totalOrders}`, 20, 62);
    doc.text(`Total Discounts: ${summary.revenue.totalDiscount.toFixed(2)}`, 20, 69);
    doc.text(`Net Revenue: ${summary.revenue.netRevenue.toFixed(2)}`, 20, 76);

    // Expenses Section
    doc.setFontSize(16);
    doc.text("Expenses Breakdown", 20, 90);
    doc.line(20, 92, 190, 92);

    doc.setFontSize(12);
    doc.text(`Total Expense: ${summary.expenses.totalExpense.toFixed(2)}`, 20, 100);
    doc.text(` - Payroll: ${summary.expenses.breakdown.payroll.toFixed(2)}`, 25, 107);
    doc.text(` - Product Cost: ${summary.expenses.breakdown.productCost.toFixed(2)}`, 25, 114);
    doc.text(` - Others: ${summary.expenses.breakdown.others.toFixed(2)}`, 25, 121);

    // Sales Section
    doc.setFontSize(16);
    doc.text("Sales Analysis", 20, 135);
    doc.line(20, 137, 190, 137);

    doc.setFontSize(12);
    doc.text(`Most Sold Category: ${summary.sales.mostSoldCategory}`, 20, 145);
    doc.text(`Items Returned: ${summary.sales.returns}`, 20, 152);
    doc.text(`Total Refunded: ${summary.sales.totalRefunded.toFixed(2)}`, 20, 159);

    // Item List (Simplified)
    doc.setFontSize(14);
    doc.text("Top Sold Items", 20, 175);
    let y = 185;
    summary.sales.items.slice(0, 10).forEach((item: any) => {
        if (y > 270) {
            doc.addPage();
            y = 20;
        }
        doc.setFontSize(10);
        doc.text(`${item.name} x ${item.quantity} - ${item.price.toFixed(2)}`, 20, y);
        y += 7;
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Pharmino POS System", 105, 290, { align: "center" });

    doc.save(`Business_Summary_${date}.pdf`);
};
